-- Add sample resources with proper structure
INSERT INTO resources (title, description, content_type, category, content_text, language, is_featured) VALUES
  ('Managing Academic Stress', 'Practical strategies for handling academic pressure and exam anxiety', 'article', 'stress_management', 'Academic stress is a common experience for college students. Here are some effective strategies to manage it: 1. Time Management - Create a schedule and stick to it. 2. Break large tasks into smaller, manageable pieces. 3. Take regular breaks during study sessions. 4. Practice relaxation techniques like deep breathing. 5. Maintain a healthy lifestyle with proper sleep, nutrition, and exercise.', 'english', true),
  
  ('Mindfulness for Mental Wellness', 'Introduction to mindfulness practices for improving mental health', 'article', 'mindfulness', 'Mindfulness is the practice of being present in the moment without judgment. Research shows it can significantly improve mental health. Benefits include: reduced anxiety and depression, improved focus and concentration, better emotional regulation, and increased self-awareness. Simple practices include: daily meditation, mindful breathing exercises, body scan techniques, and mindful walking.', 'english', true),
  
  ('Building Healthy Relationships', 'Guide to developing and maintaining positive relationships in college', 'article', 'relationships', 'Healthy relationships are crucial for mental wellness in college. Key principles include: effective communication, setting boundaries, mutual respect, trust and honesty, and emotional support. Tips for building relationships: be genuine and authentic, show interest in others, practice active listening, be reliable and trustworthy, and resolve conflicts constructively.', 'english', false),
  
  ('Sleep Hygiene for Students', 'Essential tips for better sleep quality and mental health', 'article', 'sleep', 'Good sleep is fundamental to mental health. Poor sleep can worsen anxiety and depression. Sleep hygiene tips: maintain a consistent sleep schedule, create a relaxing bedtime routine, limit screen time before bed, keep your room cool and dark, avoid caffeine and alcohol before bedtime, and use your bed only for sleep and rest.', 'english', false),
  
  ('Coping with Anxiety', 'Understanding and managing anxiety in academic settings', 'video', 'anxiety', 'This comprehensive guide covers: understanding what anxiety is, recognizing anxiety symptoms, breathing techniques for immediate relief, cognitive strategies for long-term management, when to seek professional help, and creating a personal anxiety management plan.', 'english', true),
  
  ('Depression Awareness and Support', 'Recognizing signs of depression and finding help', 'article', 'depression', 'Depression is more than just feeling sad. Key signs include: persistent sadness or hopelessness, loss of interest in activities, changes in appetite or sleep, fatigue, difficulty concentrating, and thoughts of self-harm. If you experience these symptoms, reach out for help. Treatment options include therapy, medication, lifestyle changes, and support groups.', 'english', false),

  ('Crisis Support Resources', 'Immediate help and resources for mental health crises', 'article', 'crisis_support', 'If you are experiencing thoughts of self-harm or suicide, please reach out immediately. National Suicide Prevention Lifeline: 988. Campus Crisis Support: Contact your campus counseling center. Emergency: Call 911. Remember, you are not alone and help is available 24/7.', 'english', false),

  ('Exam Stress Management', 'Techniques for managing stress during exam periods', 'article', 'stress_management', 'Exam periods can be particularly stressful. Effective strategies include: creating a study schedule, using active recall techniques, taking regular breaks, maintaining a healthy lifestyle, getting adequate sleep, practicing relaxation techniques, and seeking support when needed.', 'english', false);