// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfjlmyodmyvfmqtdafng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmamxteW9kbXl2Zm1xdGRhZm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTI5MDgsImV4cCI6MjA3Mzc4ODkwOH0.eM3Cl0kJMlw7GqslnuTA7BRyebNLNiO0V70J-Zu9ThM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});